apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: wordpress-mysql
        image: k8s/mysql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: wordpress
          - name: MYSQL_ROOT_PASSWORD
            value: password
        volumeMounts:
        - name: mysql-claim-volume
          mountPath: /var/lib/mysql
        - name: sql-setup-config
          mountPath: /docker-entrypoint-initdb.d
        - name: mymycnf-setup-config
          mountPath: /etc/my.cnf.d
      volumes:
      - name: mysql-claim-volume
        persistentVolumeClaim:
          claimName: pv-mysql-claim
      - name: sql-setup-config
        configMap:
              name: db-setup-configmap
              items:
                - key: setup.sql
                  path: setup.sql
      - name: mymycnf-setup-config
        configMap:
              name: mymycnf-setup-configmap
              items:
                - key: mymy.cnf
                  path: mymy.cnf               
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: mysql-storage
  hostPath:
    path: /private/var/lib/kubernetes/pv00
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-mysql-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: mysql-storage