apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-server
  labels:
    app: phpmyadmin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-server
  template:
    metadata:
      labels:
        app: phpmyadmin-server
    spec:
      containers:
        - name: phpmyadmin-server
          image: k8s/phpmyadmin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PMA_HOST
              value: mysql-server
            - name: PMA_USER
              value: wordpress
            - name: PMA_PASSWORD
              value: wordpress