apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-server
spec:
  type: NodePort
  selector:
    app: phpmyadmin-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30088