apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-mysql-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: mysql-storage