apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          resources:
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: mysql-pass
                    key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-claim-volume
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-conf
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-claim-volume
          persistentVolumeClaim:
            claimName: pv-mysql-claim
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-conf
          configMap:
            name: mysql-conf-config